"*sales*":
  validators:
    is_empty_dataframe: 
    required_columns:
      - product_id
      - price
      - store_id
      - sellout_price
      - date
      - quantity
    additional_columns:
      - product_id
      - price
      - store_id
      - sellout_price
      - date
      - quantity
    validate_product_ids:
      product_id_column: product_id
      product_id_master_column: product_id

"*inventory*":
  validators:
    is_empty_dataframe: 
    required_columns:
      - product_id
      - store_id
      - date
      - opening_stock
      - quantity_in
      - quantity_out
      - closing_stock
      - reorder_point
      - reorder_quantity
      - unit_cost
    additional_columns:
      - product_id
      - store_id
      - date
      - opening_stock
      - quantity_in
      - quantity_out
      - closing_stock
      - reorder_point
      - reorder_quantity
      - unit_cost
    validate_product_ids:
      product_id_column: product_id
      product_id_master_column: product_id