"*sales*":
  validators:
    is_empty_dataframe: 
    required_columns:
      - product_id
      - product_version
      - product_name
      - price
      - store_id
      - sellout_price
      - date
      - quantity
    additional_columns:
      - product_id
      - product_version
      - product_name
      - price
      - store_id
      - sellout_price
      - date
      - quantity
    check_null_values:
      columns:
        - price
        - sellout_price
        - quantity
      custom_null_values:
        - ""
        - " "
        - "NA"
        - "N/A"
        - "NULL"

    value_range:
      price:
        min: 0
        max: 100
      sellout_price:
        min: 0
      Value3:
        max: 100

"*product_mapping*":
  validators:
    is_empty_dataframe:
    required_columns:
      - Category
      - ProductId
      - ProductName
    additional_columns:
      - Category
      - ProductId
      - ProductName
    check_null_values:
      columns:
        - Category
        - ProductId
        - ProductName
      custom_null_values:
        - ""
        - " "
        - "NA"
        - "N/A"
        - "NULL"
    check_hierarchy:
      higher_level_columns:
        - Category
      lower_level_columns:
        - ProductId
        - ProductName

