steps:
  - type: dispatcher
    name: "0_dispatcher"
    registry_path: "config/0_dispatcher.yaml"
    report_path: "0_dispatcher"
    input_folder_path: "input"
    output_folder_path: null
    rm_from_input_folder: false

  - type: transform
    name: "1_transform"
    registry_path: "config/1_transform_registry.yaml"
    report_path: "1_transform"
    input_folder_path: "0_dispatcher"
    output_folder_path: null

  - type: validate
    name: "2_validation"
    registry_path: "config/2_validation_registry.yaml"
    report_path: "1_transform"
    input_folder_path: "1_transform"
    output_folder_path: "delivery"  

  # - type: custom_step
  #   name: "3_custom"
  #   registry_path: "config/3_custom_registry.yaml"
  #   report_path: "custom_reports"
  #   input_folder_path: "delivery"
  #   output_folder_path: "final_output"
  #   custom_param: "example_value"  
