steps:
  - type: dispatcher
    name: "0_dispatcher"
    registry_path: "config/0_dispatcher.yaml"
    report_folder: "reports"
    input_folder: "input"  # Corrisponde a 'input' in data_structure
    output_folder: "staging.0_dispatcher"  # Percorso completo con dot notation
    rm_from_input_folder: false

  - type: transform
    name: "1_transform"
    registry_path: "config/1_transform_registry.yaml"
    report_folder: "reports"
    input_folder: "staging.0_dispatcher"  # Input dal dispatcher
    output_folder: "staging.1_transform"   # Output in staging

  - type: validate
    name: "2_validation"
    registry_path: "config/2_validation_registry.yaml"
    report_folder: "reports"  # Changed from report_path to report_folder
    input_folder: "staging.1_transform"  # Input dal transform
    output_folder: "delivery"            # Output finale in delivery
